apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-frontend
  template:
    metadata:
      labels:
        app: pfe-frontend
    spec:
      containers:
        - name: pfe-frontend
          image: acr-chayma.azurecr.io/frontend-sbus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-chayma-secret
