apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: infrawatchchayma.azurecr.io/backend-pfe
    newTag: "latest"
